name: Build and Release Electron App

on:
  push:
    tags:
      - v*.*.* # Trigger workflow on version tags

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Ensure this secret is set correctly
