name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: win-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
